In [1]:
# Set the bases

dataset_name = "Example Semantic Model"
lakehouse_name = "SempyDemo"

StatementMeta(, 3e09b8ae-8c70-4a9a-8774-231bdcbf0ca4, 5, Finished, Available, Finished)

In [2]:
import sempy.fabric as fabric

StatementMeta(, 3e09b8ae-8c70-4a9a-8774-231bdcbf0ca4, 6, Finished, Available, Finished)

In [3]:
# Show entire table
df_table = fabric.read_table(dataset_name, "DimProduct")
df_table

StatementMeta(, 3e09b8ae-8c70-4a9a-8774-231bdcbf0ca4, 7, Finished, Available, Finished)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,Product Name,StandardCost,FinishedGoodsFlag,Color,SafetyStockLevel,...,DaysToManufacture,ProductLine,DealerPrice,Class,Style,ModelName,EnglishDescription,StartDate,EndDate,Status
0,1,AR-5381,<NA>,<NA>,<NA>,Adjustable Race,<NA>,False,NA,1000,...,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2017-07-01,NaT,Current
1,2,BA-8327,<NA>,<NA>,<NA>,Bearing Ball,<NA>,False,NA,1000,...,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2017-07-01,NaT,Current
2,12,CR-9981,<NA>,<NA>,<NA>,Crown Race,<NA>,False,NA,1000,...,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2017-07-01,NaT,Current
3,14,DC-8732,<NA>,<NA>,<NA>,Decal 1,<NA>,False,NA,1000,...,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2017-07-01,NaT,Current
4,15,DC-9824,<NA>,<NA>,<NA>,Decal 2,<NA>,False,NA,1000,...,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2017-07-01,NaT,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,599,BK-M18B-48,1,LB,CM,"Mountain-500 Black, 48",294.5797,True,Black,100,...,4,M,323.994,L,U,Mountain-500,"Suitable for any type of riding, on or off-roa...",2019-07-01,NaT,Current
602,600,BK-M18B-52,1,LB,CM,"Mountain-500 Black, 52",294.5797,True,Black,100,...,4,M,323.994,L,U,Mountain-500,"Suitable for any type of riding, on or off-roa...",2019-07-01,NaT,Current
603,604,BK-R19B-44,2,LB,CM,"Road-750 Black, 44",343.6496,True,Black,100,...,4,R,323.994,L,U,Road-750,Entry level adult bike; offers a comfortable r...,2019-07-01,NaT,Current
604,605,BK-R19B-48,2,LB,CM,"Road-750 Black, 48",343.6496,True,Black,100,...,4,R,323.994,L,U,Road-750,Entry level adult bike; offers a comfortable r...,2019-07-01,NaT,Current
605,606,BK-R19B-52,2,LB,CM,"Road-750 Black, 52",343.6496,True,Black,100,...,4,R,323.994,L,U,Road-750,Entry level adult bike; offers a comfortable r...,2019-07-01,NaT,Current

In [4]:
# Query semantic model and return table
fabric.evaluate_measure(dataset_name, \
    measure=["$ Sales", "# Orders"], \
    groupby_columns=["DimProduct[Color]"], \
    filters={"DimProduct[Color]": ["Black", "Blue", "Yellow"]})

StatementMeta(, 3e09b8ae-8c70-4a9a-8774-231bdcbf0ca4, 8, Finished, Available, Finished)

    Color       $ Sales  # Orders
0   Black  8838411.9576      9042
1    Blue    2279096.28      3747
2  Yellow  4856755.6275      4364

In [5]:
## Run query fetched from Perf. Analyzer in PBI Desktop

(fabric.evaluate_dax(
        dataset = dataset_name,
        dax_string=
        """
// DAX Query
DEFINE
	VAR __DS0FilterTable = 
		TREATAS({2020}, 'DimDate'[FiscalYear])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'DimProductSubcategory'[Sub Category Name],
			__DS0FilterTable,
			"v__Orders", 'FactInternetSales'[# Orders]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(1001, __DS0Core, [v__Orders], 0, 'DimProductSubcategory'[Sub Category Name], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[v__Orders] DESC, 'DimProductSubcategory'[Sub Category Name]


        """  
       )  
)

StatementMeta(, 3e09b8ae-8c70-4a9a-8774-231bdcbf0ca4, 9, Finished, Available, Finished)

   DimProductSubcategory[Sub Category Name]  [v__Orders]
0                           Tires and Tubes         9741
1                                   Helmets         6298
2                         Bottles and Cages         4638
3                                Road Bikes         3875
4                            Mountain Bikes         3305
5                                   Jerseys         3253
6                                      Caps         2138
7                             Touring Bikes         2083
8                                   Fenders         2071
9                                    Gloves         1408
10                                   Shorts         1014
11                                 Cleaners          888
12                          Hydration Packs          714
13                                    Socks          562
14                                    Vests          547
15                               Bike Racks          319
16                              Bike Stands          245